name: Project auto-testing
on:
  workflow_run:
    workflows: ["Polybot Service Deployment"]
    types:
      - completed

permissions: {}

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: .github/workflows/service-deploy.yaml
      - name: Parse EC2 pablic IP address
        run: |
          EC2_PUBLIC_IP=$(grep -E "EC2_PUBLIC_IP" .github/workflows/service-deploy.yaml | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' || true)
          echo -e "\n\nParsed EC2 public IP address: $EC2_PUBLIC_IP"          

          if [[ -z "$EC2_PUBLIC_IP" ]]; then
            echo -e "\n\nInvalid EC2_PUBLIC_IP env var found in .github/workflows/service-deploy.yaml"
            exit 1
          fi
          
          echo "EC2_PUBLIC_IP=${EC2_PUBLIC_IP}" >> "$GITHUB_ENV"

      - name: Test Docker Compose project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            
            curl -O -L https://raw.githubusercontent.com/alonitac/PolybotServiceDocker/main/test/test-compose-project.sh
            bash test-compose-project.sh

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: |
          echo "Your Polybot Service Deployment workflow should be completed successfully first"
          exit 1